[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
equilibrium_core = "1uu1R8otFuC235hhTstPWVUwsuZ1z5cLoKYd1biVv8Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users//.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
